### ISSUE TITLE
楼中楼 UI 错位

### ISSUE THREAD

**Issue by FWangZil** [coolpace/V2EX_Polish#10]
这个帖子 https://www.v2ex.com/t/933468#reply92

<img width="839" alt="image" src="https://user-images.githubusercontent.com/20198261/232952021-9d1d38fa-1aad-4e9e-82b9-69c73a95b563.png">

**Comment by Codennnn** [comment]
我看到是正常的，昨天也有人反馈过[这个问题](https://www.v2ex.com/t/930155?p=4#r_12963670)。看看你是不是在站内设置了“自定义 CSS”，或者有同时安装了相关的别的脚本或浏览器扩展，导致样式发生冲突。

![image](https://user-images.githubusercontent.com/47730755/232954976-f181094b-ef31-4f6c-8e31-e8ee185b240d.png)

**Comment by hueralin** [comment]
> 我看到是正常的，昨天也有人反馈过[这个问题](https://www.v2ex.com/t/930155?p=4#r_12963670)。看看你是不是在站内设置了“自定义 CSS”，或者有同时安装了相关的别的脚本或浏览器扩展，导致样式发生冲突。
> 
> ![image](https://user-images.githubusercontent.com/47730755/232954976-f181094b-ef31-4f6c-8e31-e8ee185b240d.png)

雀食，去掉自定义 css 就好了

**Comment by FWangZil** [comment]
> > 我看到是正常的，昨天也有人反馈过[这个问题](https://www.v2ex.com/t/930155?p=4#r_12963670)。看看你是不是在站内设置了“自定义 CSS”，或者有同时安装了相关的别的脚本或浏览器扩展，导致样式发生冲突。
> > ![image](https://user-images.githubusercontent.com/47730755/232954976-f181094b-ef31-4f6c-8e31-e8ee185b240d.png)
> 
> 雀食，去掉自定义 css 就好了

原来如此，感谢
