### ISSUE TITLE
你好，插件上传图片失败了

### ISSUE THREAD

**Issue by CC11001100** [coolpace/V2EX_Polish#101]
你好，今天发现发帖时粘贴图片无法自动上传了

看了下控制台有报错：
<img width="1722" alt="image" src="https://github.com/user-attachments/assets/4cc98b1b-eca3-4670-a31e-4276332027d2">
跟进去代码是这个请求报的错误： 
<img width="1104" alt="image" src="https://github.com/user-attachments/assets/6fc2fefe-b8f8-4486-9c52-255e7d660d86">
clientId是"81be04b9e4a08ce"
看Network中显示也是400：
<img width="1664" alt="image" src="https://github.com/user-attachments/assets/c0d06fee-266c-4d22-8b86-1701f1bb6f63">

**Comment by Codennnn** [comment]
这应该不是插件的问题，你把插件关闭再重开试试。
