### ISSUE TITLE
Safari无法打开夜间模式和选项设置

### ISSUE THREAD

**Issue by Snuff-red** [coolpace/V2EX_Polish#103]
### 📝 问题描述

Safari无法打开夜间模式和选项设置

### 📷 截图或示例

<img width="795" alt="image" src="https://github.com/user-attachments/assets/3114f57a-cfe9-4dd5-8041-e0a6969646c6">

### 🚀 其他信息
M1pro，Macos15.1，打开了Apple intelligence

**Comment by Codennnn** [comment]
更新到最新的脚本就能修复这个问题了
