### ISSUE TITLE
safari 浏览器，首页正常渲染，但是进入帖子内不能渲染。

### ISSUE THREAD

**Issue by dingangui** [coolpace/V2EX_Polish#104]
### 📝 问题描述
硬件：Macbook Pro M1 Pro
系统：MacOS 15.0.1 
Safari：版本18.0.1 (20619.1.26.31.7)
插件版本：1.11.6

在 safari 浏览器使用 userscripts 加载插件，浏览 v2ex 的首页时，插件正常工作，但是点进某个帖子后，又回到 v2ex 官方的默认主题效果。

查看开发工具，进入帖子后，控制台报错：SyntaxError: Can't create duplicate variable: 'topicId'

### 📷 截图或示例

**首页正常渲染**
<img width="1920" alt="Snipaste_2024-11-04_10-07-08" src="https://github.com/user-attachments/assets/2db89321-7d84-4f61-af4e-37bf605514e0">

**进入帖子后，渲染出错**
<img width="1920" alt="Snipaste_2024-11-04_10-06-37" src="https://github.com/user-attachments/assets/0e30ef3e-02bb-4a10-a237-30988cbd8855">

**出错位置**
<img width="1024" alt="Snipaste_2024-11-04_10-13-36" src="https://github.com/user-attachments/assets/95b63e35-3fee-4ce9-8015-ed3662a07b16">

**Comment by Codennnn** [comment]
我更新了 greasy fork 的脚本，修复了这个问题
