### ISSUE TITLE
预览时多个滚动条

### ISSUE THREAD

**Issue by orionna319** [coolpace/V2EX_Polish#108]
### 📝 问题描述

多个滚动条，去掉这块就好了[overflow-y: auto](https://github.com/coolpace/V2EX_Polish/blob/de46ae77a5d267d931552fd8c97f2d7c759046ff/src/styles/v2ex-effect.scss#L378)

### 📷 截图或示例

![image](https://github.com/user-attachments/assets/e2762b23-65ac-4480-abb8-ef9ea26a90e1)

### 🚀 其他信息

版本
2.2.0

**Comment by vczhan** [comment]
F12看直接是套iframe，之前是调接口渲染吗？
