### ISSUE TITLE
作者以回复的形式@多个用户时，楼中楼需要分别显示

### ISSUE THREAD

**Issue by orzyyyy** [coolpace/V2EX_Polish#11]
如[这里的三楼和六楼](https://www.v2ex.com/t/933686#r_12968666)，六楼看上去就像是作者没回复。

**Comment by Codennnn** [comment]
这个问题也有人[反馈过](https://github.com/coolpace/V2EX_Polish/discussions/1#discussioncomment-5655527)。”楼中楼”的实现依靠的是定位到某一个用户的某一条回复，然而，在一条回复中同时回复多人，打破了这个约定。按现在的能力，没法将一条回复拆开多个回复分别进行嵌套，希望你能理解。
