### ISSUE TITLE
点击筛选热门评论按钮不响应

### ISSUE THREAD

**Issue by dustookk** [coolpace/V2EX_Polish#12]
不知道什么时候开始， “xx条热门回复” 变成了文字，不响应点击事件了。
所有程序都是最新版本。

**Comment by Codennnn** [comment]
触发按钮移动到人物信息卡片下面了：
![Snipaste_2023-04-19_17-54-17](https://user-images.githubusercontent.com/47730755/233039073-ecd83639-05d4-4237-8787-2a0af63cfddf.jpg)

**Comment by dustookk** [comment]
谢谢回复
