### ISSUE TITLE
楼层数显示在有block用户存在的时候会出现错误

### ISSUE THREAD

**Issue by starrystarg** [coolpace/V2EX_Polish#13]
我浏览一个帖子时发现有许多人回复 #18 楼层的用户，但我发现 #18 楼层用户的内容并不构成回复条件，所以我在未登录状态下查看发现这个用户是我 block 过的，所以不显示。但是他的楼层数 #18 会被顺移至下一楼层，也就是原本#19的用户上去了（实际上是#20，因为他在之前的楼层发过了一条评论，楼层数又递减一层），导致了 bug。
![ihAeF5.png](https://i.328888.xyz/2023/04/21/ihAeF5.png)
![ihA7f3.png](https://i.328888.xyz/2023/04/21/ihA7f3.png)

**Comment by Codennnn** [comment]
层数的渲染是由原站点决定的，实际上扩展是无法得知你屏蔽了哪个用户的，所以也就无法修正楼层。

**Comment by Codennnn** [comment]
这其实算是 V2EX 评论逻辑的缺陷。

**Comment by starrystarg** [comment]
> 层数的渲染是由原站点决定的，实际上扩展是无法得知你屏蔽了哪个用户的，所以也就无法修正楼层。

明白了，谢谢你的解惑😃
