### ISSUE TITLE
手机狐猴浏览器安装完显示有问题

### ISSUE THREAD

**Issue by tuutoo** [coolpace/V2EX_Polish#15]
![Screenshot_2023-04-30-00-44-48-535_com lemurbrowser exts](https://user-images.githubusercontent.com/9068314/235314177-2197ab2d-ad46-4cdd-8e5d-22d56f4e0473.jpg)

**Comment by Codennnn** [comment]
现在不适配移动端哦

**Comment by tuutoo** [comment]
好的 了解

谢谢

LeoKu ***@***.***> 于 2023年4月30日周日 09:20写道：
