### ISSUE TITLE
是否支持解析页面中的 Base64？

### ISSUE THREAD

**Issue by NASLIGHTSABER** [coolpace/V2EX_Polish#17]
鉴于站内太多base64编码后的信息 能不能......

**Comment by Codennnn** [comment]
能不能解析 Base64 信息？

有的，右键打开菜单就可以找到解析 Base64 的操作。

<img width="835" alt="image" src="https://user-images.githubusercontent.com/47730755/236656386-01b09d1a-46b1-4279-bb7a-5983882db36e.png">

**Comment by Codennnn** [comment]
## aaa

| qqwdfqw | sdsdsff | ddfg |   | dfgfd |
| --- | --- | --- | --- | --- |
|   |   |   |   | asfddfgfd |

**Comment by Codennnn** [comment]
## aaa

| qqwdfqw | sdsdsff | ddfg |   | dfgfd |
| --- | --- | --- | --- | --- |
|   |   |   |   | asfddfgfd |

**Comment by listenerri** [comment]
@Codennnn firefox 中右键菜单没有可选项

firefox 版本：117.0 (64 位)

![图片](https://github.com/coolpace/V2EX_Polish/assets/7995379/4e6569aa-1957-450b-af7e-ef76ef2c97c7)

**Comment by Codennnn** [comment]
@listenerri 需要进到主题内容页才展示选项，列表页没有这个功能。

**Comment by listenerri** [comment]
> @listenerri 需要进到主题内容页才展示选项，列表页没有这个功能。

在主题内容页也没有菜单项的

**Comment by Codennnn** [comment]
你的插件版本是？

**Comment by listenerri** [comment]
作者 [LeoKu](https://addons.mozilla.org/zh-CN/firefox/user/17801507/?utm_source=firefox-browser&utm_medium=firefox-browser&utm_content=addons-manager-user-profile-link)
版本 1.6.9
上次更新 2023年9月4日

今天刚安装的

**Comment by listenerri** [comment]
测试链接：https://www.v2ex.com/t/963839

![图片](https://github.com/coolpace/V2EX_Polish/assets/7995379/a2296e7a-04f2-426f-8d77-3273d0bffc13)

**Comment by Codennnn** [comment]
v1.6.10 已修复上下文菜单项丢失的问题，感谢你提供的反馈～

![Uploading image.png…]()

**Comment by listenerri** [comment]
@Codennnn 测试了两个网页，菜单项出来了，但解码似乎不能正常工作

![图片](https://github.com/coolpace/V2EX_Polish/assets/7995379/24d8fc09-f25e-4e1c-8e9a-17b443b56f9a)

**Comment by Codennnn** [comment]
v1.6.11 修复了解码问题～
