### ISSUE TITLE
夜间模式无效

### ISSUE THREAD

**Issue by hobyleo** [coolpace/V2EX_Polish#19]
点击切换夜间模式后，没有生效

**Comment by hobyleo** [comment]
> 是否设置了跟随系统切换主题？ <img alt="image" width="333" src="https://user-images.githubusercontent.com/47730755/237111196-4e3d1b05-b22f-4f10-b1f8-afe1b5f1afbe.png">

没有设置

**Comment by Codennnn** [comment]
那请提供更详细的复现步骤
