### ISSUE TITLE
firefox不会自动开启v2ex polish的效果

### ISSUE THREAD

**Issue by luzibuye** [coolpace/V2EX_Polish#22]
firefox不会自动开启v2ex polish的效果，需要点击插件才会更改样式，但是点进主题之后又会变为原始站点的样式。不知道是不是我哪里使用不对。
firefox版本是113.0.1，m1芯片。

**Comment by Codennnn** [comment]
Firefox 是这样的，要选择“总是允许”启用扩展：
![image](https://github.com/coolpace/V2EX_Polish/assets/47730755/ff0720d9-d984-4ee6-9a48-a59d46fe1f29)

**Comment by luzibuye** [comment]
还真是，感谢！
