### ISSUE TITLE
建议有新的未读消息时能在图标上显示条数

### ISSUE THREAD

**Issue by Jonnyan404** [coolpace/V2EX_Polish#24]
可参考v2ex plus的设计

**Comment by Codennnn** [comment]
查看了V2EX Plus 的实现代码：https://github.com/sciooga/v2ex-plus/blob/master/background/notifications.js

个人觉得此功能实现不太优雅，故就此搁置。

**Comment by Codennnn** [comment]
现已支持展示未读消息的数量：

![image](https://github.com/coolpace/V2EX_Polish/assets/47730755/66d02670-e0f0-4b0c-b1c4-f74adbdf9c7e)
