### ISSUE TITLE
点赞失败后，状态显示错误

### ISSUE THREAD

**Issue by ily433664** [coolpace/V2EX_Polish#26]
点赞有时候会提示“CRSF 字符串失效，请重新点击一次”，但是页面显示是已经点赞了，并且刷新页面后，点赞过的爱心也还在
![微信截图_20230522111251](https://github.com/coolpace/V2EX_Polish/assets/30280772/6a156888-42c3-4f57-8805-764e902fb2f7)

**Comment by Codennnn** [comment]
确实存在这个问题，我找时间修一修
