### ISSUE TITLE
楼中楼回复错乱了

### ISSUE THREAD

**Issue by JZLeung** [coolpace/V2EX_Polish#32]
https://www.v2ex.com/t/946150#reply34

3 楼（讨论机箱）和 10 楼（讨论显卡）均为同一个人回复的，然后另外的同一个人也不按顺序的回复了这两条，导致直接错乱了。

18楼应该是回复到14楼。
34楼应该是回复到15楼

**Comment by Codennnn** [comment]
因为现实就是无法判断他们想回复哪个楼层，除非他们在回复中明确指定楼层号（像这样： #123）

**Comment by Codennnn** [comment]
**为什么有的「楼中楼」回复的楼层不正确？** 更具体的原因如下：

> 由于 V2EX 的原回复并没有记录回复的楼层，本扩展只能根据被回复的用户去寻找此用户的最近一条回复，然后嵌入到这后面去，这种方法并不能保证正确识别用户真正要回复的是哪一个楼层。
