### ISSUE TITLE
控制台报错：Uncaught ReferenceError: $ is not defined，需要重新安装扩展

### ISSUE THREAD

**Issue by JZLeung** [coolpace/V2EX_Polish#34]
```bash
Uncaught ReferenceError: $ is not defined
    at v2ex-topic.min.js:302:17
```

浏览器：Edge 版本 114.0.1823.43 (正式版本) (64 位)
UserAgent：5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.43

控制台中能正常使用 jQuery 的 `$` 函数。

**Comment by Codennnn** [comment]
我测了一下，确实存在这个问题，重新安装扩展就可以了，谢谢反馈！
