### ISSUE TITLE
1.4.18版本在FireFox下无法文字转Base64失败

### ISSUE THREAD

**Issue by rhettor** [coolpace/V2EX_Polish#36]
提示该文本无法编码为Base64，在1.4.17也能复现

**Comment by Codennnn** [comment]
请提供下你的文本，我调试一下，看看是什么问题。

**Comment by rhettor** [comment]
@Codennnn 输入任何文本都是一样的效果，有无办法抓取日志来分析

**Comment by rhettor** [comment]
> 请提供下你的文本，我调试一下，看看是什么问题。

输入任何文本都是一样的效果，有无办法抓取日志来分析

**Comment by rhettor** [comment]
https://github.com/coolpace/V2EX_Polish/assets/8852109/18c9d6ac-f77c-4ba4-9662-a3d17fd49dc7

问题视频

**Comment by Codennnn** [comment]
你用的浏览器是什么？

**Comment by rhettor** [comment]
> 你用的浏览器是什么？

FireFox 114.0.2 (64 位)

**Comment by Codennnn** [comment]
OK  确实是 Firefox 上会出现的问题，Chrome 没发现有这个问题，我修一下

**Comment by Codennnn** [comment]
找到原因了，Firefox 扩展中无法使用 `window.encodeURIComponent`，所以我通过判断禁用了encodeURIComponent，这样导致的后果是无法将包含中文的文本编码为 Base64。

**Comment by Codennnn** [comment]
找到原因了，Firefox 扩展中无法使用 `window.encodeURIComponent`，所以我通过判断禁用了encodeURIComponent，这样导致的后果是无法将包含中文的文本编码为 Base64。

**Comment by rhettor** [comment]
> 找到原因了，Firefox 扩展中无法使用 `window.encodeURIComponent`，所以我通过判断禁用了encodeURIComponent，这样导致的后果是无法将包含中文的文本编码为 Base64。

👍

**Comment by rhettor** [comment]
@Codennnn 更新到1.5.2还是有问题，中文和数字无法编码，英文出现乱码

**Comment by Codennnn** [comment]
编码中文需要用到 window.encodeURIComponent，但是 Firefox 扩展中用不了这个方法，所以会有这个问题。

**Comment by rhettor** [comment]
> 编码中文需要用到 window.encodeURIComponent，但是 Firefox 扩展中用不了这个方法，所以会有这个问题。

但是英文和数据base64出来的结果也是错误的
