### ISSUE TITLE
增加使用v2ex默认颜色主题

### ISSUE THREAD

**Issue by smallc2009** [coolpace/V2EX_Polish#37]
插件app做的很好，开启了之后使用自带的主题和UI也很好看，但白色有点过于亮眼，希望增加选项来支持使用原v2ex配色。

**Comment by Codennnn** [comment]
正在计划开发多主题功能，满足大家对网页装扮的个性化需求。

**Comment by Codennnn** [comment]
V2EX Polish 增加了一个暖色调的主题，快试试看吧：
<img width="1358" alt="image" src="https://github.com/user-attachments/assets/dc0b31af-6ada-4268-b684-a26e089bf232">
<img width="1226" alt="image" src="https://github.com/user-attachments/assets/9d1819cf-fb75-4606-8d7c-56413c3a0e17">
