### ISSUE TITLE
建议在预览中增加附言

### ISSUE THREAD

**Issue by yunfan777** [coolpace/V2EX_Polish#38]
作者你好，你的插件用的挺爽的。发现一点小问题，在预览界面中，没有OP的附言。建议后续增加
![Screenshot 2023-08-08 at 09_mosaic](https://github.com/coolpace/V2EX_Polish/assets/4952175/0b76b43b-6b46-4669-bef9-dc6783c29274)
![Screenshot 2023-08-08 at 09_mosaic (1)](https://github.com/coolpace/V2EX_Polish/assets/4952175/160a9ea7-4c06-4d8c-8aa5-1109dbbd138a)

**Comment by Codennnn** [comment]
v1.6.2 中已支持在预览内容中展示附言。
