### ISSUE TITLE
深色模式的页面感觉有些暗，希望可以优化一下

### ISSUE THREAD

**Issue by jhxxs** [coolpace/V2EX_Polish#4]
扩展很棒，已经在用了。目前感觉深色模式下的对比度比较低，看起来不是很清楚。
我用 userscript 参考 GitHub 的界面简单魔改了一下深色模式下的背景和字体颜色：

1. 首页

魔改前：
![image](https://user-images.githubusercontent.com/7448223/230537123-44d8e663-dcf2-4623-8f7d-41e6e0a3b0ca.png)

魔改后：
![Snipaste_2023-04-07_11-44-13](https://user-images.githubusercontent.com/7448223/230536959-4b06ce26-0e76-412f-8913-1f15751cc7f5.png)

2. 详情页

魔改前：
![image](https://user-images.githubusercontent.com/7448223/230537445-c6638bc2-918d-401a-b3b1-6d8c61b21e4a.png)

魔改后：
![Snipaste_2023-04-07_11-43-35](https://user-images.githubusercontent.com/7448223/230537034-921604ad-4702-4da7-ad59-f2abb10e1e5b.png)

**Comment by Codennnn** [comment]
更改后的效果非常棒，后续会考虑添加一个类 GitHub 配色的主题。

**Comment by Aloento** [comment]
创持
