### ISSUE TITLE
能否提供关闭楼中楼回复的功能？

### ISSUE THREAD

**Issue by sunaowei** [coolpace/V2EX_Polish#43]
从目前的实际使用情况来看，受限于V站自身的内容形式，导致楼中楼的回复经常错乱。目前默认开启，不支持关闭。

那么能否提供一种关闭楼中楼的方法？

**Comment by Codennnn** [comment]
<img width="433" alt="image" src="https://github.com/coolpace/V2EX_Polish/assets/47730755/c56aa0bd-a467-4ae3-bfe7-31bda4cbf348">

v1.6.5 中添加了关闭「楼中楼」功能的选项。
