### ISSUE TITLE
首页列表优化阅读效率

### ISSUE THREAD

**Issue by 0x7a7a** [coolpace/V2EX_Polish#44]
现在的样式可能以美观为主,但阅读效率较低(一页只能看到7-8条标题)

能否增加一些选项适配不同的需求,例如:
- 内容丰富.比如像现在这样,在一个`<li>`里面填充许多相关内容
- 简约高效.只显示最为关键的信息,这样列表内容更密集

*插件不错,还在观望,谢谢作者*

**Comment by 0x7a7a** [comment]
顺带说一句,是否可以增加一个选项处理评论(不修改原始评论显示方式)
楼中楼显示应该全部在前端计算对比,不知道会影响多少性能

**Comment by Codennnn** [comment]
为了美观确实减少了展示的内容，但我觉得这样比起在拥挤的空间内的文字来说，其实是更加易读的。

**Comment by Codennnn** [comment]
<img width="417" alt="image" src="https://github.com/coolpace/V2EX_Polish/assets/47730755/fb7d69ef-b248-4075-b118-e445a5926f41">

在设置里面可以关闭「楼中楼」功能。

**Comment by 0x7a7a** [comment]
> 为了美观确实减少了展示的内容，但我觉得这样比起在拥挤的空间内的文字来说，其实是更加易读的。

现在可能更需要的是效率,一眼扫过去发现自己感兴趣的,没兴趣的就关了,我个人是有类似需求,可以再看看别人的反馈.
样式上甚至可以给个选项,还原成默认那样我觉得也不错,类似楼中楼这个选项
