### ISSUE TITLE
在系统时黑暗模式的情况下，刷新或者进入帖子都会从亮色变为黑色

### ISSUE THREAD

**Issue by taurusxin** [coolpace/V2EX_Polish#45]
如题，在网页未完全加载时，默认的白色主题，只有加载完会变成黑色主题，有办法解决吗？

在晚上看帖子一下白一下黑的会很亮眼

**Comment by Codennnn** [comment]
如果你用的是 Firefox 的话就会有这种情况出现，目前没办法解决呢

**Comment by taurusxin** [comment]
> 如果你用的是 Firefox 的话就会有这种情况出现，目前没办法解决呢

是 Chrome 呢，好吧

**Comment by Codennnn** [comment]
用的是油猴脚本还是扩展？

**Comment by subframe7536** [comment]
v1.7.4 + chrome 117 也存在这种情况
![repro](https://github.com/coolpace/V2EX_Polish/assets/78338239/3c6c17ad-d9f9-4294-9b51-c5b6a4160d45)

**Comment by Codennnn** [comment]
v1.7.5 修复了这个问题，先前这个问题只发生在开启「自动跟随系统主题」选项后。
