### ISSUE TITLE
预加载多页回复失败

### ISSUE THREAD

**Issue by zigaai** [coolpace/V2EX_Polish#47]
![a](https://github.com/coolpace/V2EX_Polish/assets/50167241/65bb4f0d-2009-4a65-b708-b6b89373c7db)

chrome版本: 
Google Chrome | 117.0.5938.89 (正式版本) （64 位）
-- | --
修订版本 | be6afae4721209be42944bbcd325665f9f44563b-refs/branch-heads/5938_62@{#9}
操作系统 | Windows 10 Version 21H2 (Build 19044.3448)
JavaScript | V8 11.7.439.16
用户代理 | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36

**Comment by Codennnn** [comment]
看了一下，只有这个主题预加载失败，其他主题都是正常的，所以无法判断错误的原因。
