### ISSUE TITLE
建议增加网址 https://origin.v2ex.com/

### ISSUE THREAD

**Issue by ageovb** [coolpace/V2EX_Polish#49]
![image](https://github.com/coolpace/V2EX_Polish/assets/62172819/a085c1fe-3fa9-4995-93bc-ee6e2cde7dd5)

**Comment by Codennnn** [comment]
这个域名有什么特殊之处吗？V2EX 的域名太多了，根本支持不过来，目前支持了 `www.v2ex` 和 `cn.v2ex`。
