### ISSUE TITLE
There is a gif coudn't load in the repository home page "README.md" module 

### ISSUE THREAD

**Issue by gricn** [coolpace/V2EX_Polish#50]
- When opening the repository, I found there is a GIF could not load.

<img width="873" alt="Snipaste_2023-11-11_22-51-25" src="https://github.com/coolpace/V2EX_Polish/assets/34237589/210086ec-6287-413d-946b-8c12ad0f7ab4">

- So I open the dev tool to check what really happened.

<img width="1728" alt="Snipaste_2023-11-11_22-30-20" src="https://github.com/coolpace/V2EX_Polish/assets/34237589/cff71699-1ca5-40db-a3a4-b295a639382c">

- And then I check the source code and find the `camo.githubusercontent.com` return status 404 and the text in the body part hints "Content length exceeded".

<img width="1728" alt="Snipaste_2023-11-11_22-48-31" src="https://github.com/coolpace/V2EX_Polish/assets/34237589/3ad492b7-7382-4a7a-9915-963299c1c637">

- So I checked the gif file code in the README.md and I find it is uploaded to the `imgur.com`. And the file size is about 7MB. And according to the solution in this [stackoverflow page](https://stackoverflow.com/questions/37750270/unable-to-embed-a-gif-on-imgur-to-a-readme-md-on-github/46701929#46701929), you could use some tool to compress the gif file to make its size below 5MB, upload and update the latest url link in the imgur.com. Maybe that could solve the problem.

At last, I love this tool very much and thanks for your hard working. Hope this comment could help you solve this problem.

**Comment by Codennnn** [comment]
Thank you very much for bringing up this issue. Your reminder has made me aware of the problem and helped me to address it better, thank you!
