### ISSUE TITLE
打开插件无法复制网页内容

### ISSUE THREAD

**Issue by tianjiaoshanzai** [coolpace/V2EX_Polish#53]
从某天开始突然无法复制粘贴，InPrivate模式只留下如下三个插件依然无法复制内容，ctrl+A也无反应
![image](https://github.com/coolpace/V2EX_Polish/assets/38492739/8225d7b2-c5e2-4f6f-a9d2-f69ca3d94c9e)

**Comment by Codennnn** [comment]
应该是选择文本的样式效果失效了，能否告知一下你现在使用的浏览器、操作系统、插件的版本？

**Comment by tianjiaoshanzai** [comment]
> 应该是选择文本的样式效果失效了，能否告知一下你现在使用的浏览器、操作系统、插件的版本？

Edge浏览器，版本 121.0.2277.4 (正式版本)
OS 名称:          Microsoft Windows 11 家庭中文版
OS 版本:          10.0.22635 暂缺 Build 22635
V2EX Polish：  1.8.4
Bitwarden - 免费密码管理器： 2023.12.1
Proxy SwitchyOmega： 2.5.20

**Comment by Codennnn** [comment]
重装插件还会有这个问题吗？

**Comment by tianjiaoshanzai** [comment]
> 重装插件还会有这个问题吗？

会的，文件和商店重装以后重启浏览器，都不能复制

**Comment by Codennnn** [comment]
> 会的，文件和商店重装以后重启浏览器，都不能复制

可以复制吧，只是没有选中文本的效果。

**Comment by Codennnn** [comment]
v1.8.5 中修复了这个问题。
