### ISSUE TITLE
无法google登陆

### ISSUE THREAD

**Issue by wxyShine** [coolpace/V2EX_Polish#55]
![image](https://github.com/coolpace/V2EX_Polish/assets/42802152/fff80309-0967-406e-b0eb-fe65160ab1f6)
今天清理下浏览器cookie  发现点登陆  没反应 一直刷新当前页面

**Comment by Codennnn** [comment]
此问题与插件无关，可以试下关闭插件排查问题所在。

**Comment by Codennnn** [comment]
看看控制台有没有报错提示？

**Comment by wxyShine** [comment]
> 看看控制台有没有报错提示？

![image](https://github.com/coolpace/V2EX_Polish/assets/42802152/3f2a8d69-1393-4b96-ac25-f58ed5a38307)
我刚退出重新尝试了，你那边可以尝试复现下！

**Comment by Codennnn** [comment]
试下在只安装 V2EX Polish 的情况下，还会不会出错？

**Comment by haoliplus** [comment]
> > 看看控制台有没有报错提示？
> 
> ![image](https://private-user-images.githubusercontent.com/42802152/296150288-3f2a8d69-1393-4b96-ac25-f58ed5a38307.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyMzczMDgsIm5iZiI6MTcwNjIzNzAwOCwicGF0aCI6Ii80MjgwMjE1Mi8yOTYxNTAyODgtM2YyYThkNjktMTM5My00Yjk2LWFjMjUtZjU4ZWQ1YTM4MzA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDAyNDMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4MjM2NWE5YzQ5MTdhMDM5ZWExYmNjY2YyMTM4ZTlhZGI1OTJlNWY0M2RhNTZhMzE4YTVjNWQyY2EyOGY1ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PLYHo9N6PyZ6Ou8xb9rsZvN5Pnk92yJRmZnRwL4Pl2c) 我刚退出重新尝试了，你那边可以尝试复现下！ 不知道是不是和其他什么插件冲突还是啥原因，不过禁用V2EX_Polish 就可以成功登陆了

同样的问题，只留下polish还是没有跳转到google的登录上，关闭polish后就可以sign in with google了

**Comment by Codennnn** [comment]
@wxyShine @haoliplus 
v1.9.10 已修复无法正常登录跳转的问题：https://github.com/coolpace/V2EX_Polish/commit/16ae6c97e411b889580daf81dc9d8ac0d49f0fcd

**Comment by haoliplus** [comment]
@Codennnn 我使用的版本是Chrome应用商店里的1.9.9，仍有这个问题。是需要其他操作吗？重装/缓存/cookies什么的？

**Comment by Codennnn** [comment]
@haoliplus 刚刚才发布最新版本，要等商店审核通过，估计下午就能更新了
