### ISSUE TITLE
内容布局设置中可否增加根据 **帖子正文+回复** 的整体长度自动切换分单栏和双栏显示呢？

### ISSUE THREAD

**Issue by Mlearn** [coolpace/V2EX_Polish#56]
首先这个插件非常棒！其中水平排列的主题内容布局对当前显示器普遍都1920+宽度的情况下确实非常有用，将主题内容和回复在两栏，方便各自上下浏览。

但是在使用中感觉希望能增加一个功能更好，即：是否能在主题内容布局中设置根据 **帖子正文+回复** 的整体长度自动确定是否以水平（双栏）显示呢？长度的确定方式可以不那么精确，（比如根据正文和帖子的整体字数来确定？）。主要是为了避免在有的帖子内容只有几行字，回复也不多或还没有回复的情况下，水平布局导致整个页面的主体内容都跑到了屏幕最左侧，一来整体看起来重心不稳，不美观，另外阅读起来感受也不舒服。

本人对前端不是很了解，不知这种需求是否合理。

总之，谢谢这么好的插件！

**Comment by Codennnn** [comment]
![image](https://github.com/coolpace/V2EX_Polish/assets/47730755/b6ba504a-e117-44e5-b993-ba489c13af1e)

已支持自动布局。

**Comment by Mlearn** [comment]
看到了，但是看起来自动的判断标准是以主题帖子内容长度为判断标准的，还是与我预期的不一样，因为我觉得，可能回复多了之后一样也是需要双排布局的。

虽然 issue closed 了，但希望能够考虑后续优化？
