### ISSUE TITLE
能否把忽略主题这个按钮做在主题列表上

### ISSUE THREAD

**Issue by hhjswf** [coolpace/V2EX_Polish#57]
有时候对某个主题比较厌恶，又不得不捏着鼻子点进去忽略这个主题，这个体验怪糟心的

**Comment by Codennnn** [comment]
可以在列表上直接屏蔽主题了：
<img width="729" alt="image" src="https://github.com/coolpace/V2EX_Polish/assets/47730755/577e7e25-99a8-49ba-b59b-2f8353d2532f">
