### ISSUE TITLE
新版插件，在Vivaldi浏览器的侧边栏一直会有这样的空页面，无法彻底关闭。

### ISSUE THREAD

**Issue by shao222** [coolpace/V2EX_Polish#59]
![image](https://github.com/coolpace/V2EX_Polish/assets/1249351/68ef362a-4a09-4bfb-98c4-c9faa78a8ef7)

插件版本：1.9.7

**Comment by Codennnn** [comment]
我这儿是可以关闭的：
![image](https://github.com/coolpace/V2EX_Polish/assets/47730755/9e676a25-65de-493a-8dd0-302231b333a1)

**Comment by WhiteNightMo** [comment]
同样遇到这个问题，插件版本1.10.7，Vivaldi版本6.7.3329.29

只要启动插件，侧边面板就会多出一个图标，右击图标-编辑-从工具栏删除，下次启动也还会出现，只有关闭插件才会消失。
![image](https://github.com/coolpace/V2EX_Polish/assets/19233023/e826f74f-dc93-4649-85f0-6429e03451b1)

经过详细观察，这个图标的链接内容其实是插件的更多设置选项，但是如果我刚打开浏览器还没打开v站，那链接内容是空白的about:blank，有点搞~
大佬们考虑兼容一下Vivaldi的奇葩情况么，强迫症实在不习惯侧边栏多出来一个无法删掉的图标啊~
![image](https://github.com/coolpace/V2EX_Polish/assets/19233023/2a3da604-5d3c-4323-97cb-5daa227cc7fa)
