### ISSUE TITLE
期望支持自定义css

### ISSUE THREAD

**Issue by zhheo** [coolpace/V2EX_Polish#6]
v2ex大多都是做过开发的，写个css应该没什么大问题吧，可以设置一个用户规则>默认规则>v2ex原生。这样应该就没人老说什么亮色太亮这个问题了。
（主要是我想帮忙设计一下，下载下来才发现我完全不会去做调试hhh，没开发过插件）

**Comment by Codennnn** [comment]
其实 V2EX 的用户设置里面就支持自定义 CSS。

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/47730755/230917837-4a700b54-b24d-4f1d-b79e-66523478d2fd.png">

如果你想帮忙开发或调试功能的话，可以阅读[这份指南](https://github.com/coolpace/V2EX_Polish/blob/main/.github/CONTRIBUTING.md)。
