### ISSUE TITLE
楼中楼被回复楼层的悬浮窗，被挡住了

### ISSUE THREAD

**Issue by jhy1234** [coolpace/V2EX_Polish#64]
如图，楼中楼，鼠标悬浮在被回复楼层的发帖者名字上时，弹出的悬浮窗会被楼中楼挡住

![Screenshot_2024-02-05_10-27-14](https://github.com/coolpace/V2EX_Polish/assets/38813998/72f8a800-e9c6-4692-a8e2-2f9d5fd2be70)

另一个例子
![Screenshot_2024-02-05_10-26-49](https://github.com/coolpace/V2EX_Polish/assets/38813998/f9e5047b-b863-4432-974d-309a25014420)

**Comment by Codennnn** [comment]
这个悬浮框不是 V2EX Polish 实现的，所以无法解决你的问题。

**Comment by jhy1234** [comment]
> 这个悬浮框不是 V2EX Polish 实现的，所以无法解决你的问题，你可以联系这个功能的作者。

确实是v2ex-plus的功能。抱歉了
