### ISSUE TITLE
帮忙让V2EX Polish也爱上s.v2ex.com吗？

### ISSUE THREAD

**Issue by Leizhenpeng** [coolpace/V2EX_Polish#68]
在Google中搜索V2EX时，它总是把我带到https://s.v2ex.com这个神秘的地方。但是，我发现V2EX Polish似乎对这个新朋友有点害羞，不愿意去那里玩耍。

讨论区（[这里](https://github.com/coolpace/V2EX_Polish/discussions/1?sort=new#discussioncomment-8316003)）看到了一些关于这个话题的讨论，看来我不是唯一一个期待你们能扩展一下V2EX Polish的社交圈的。

**Comment by Codennnn** [comment]
已支持匹配 `s.v2ex.com`。

**Comment by Leizhenpeng** [comment]
赞
