### ISSUE TITLE
稍后阅读怎么看不到文章列表

### ISSUE THREAD

**Issue by shenweiyan** [coolpace/V2EX_Polish#70]
如题，不知道是不是我的打开方式不对，还是有什么地方忽略了~

问题一：**稍后阅读**好像要进入到具体的帖子才显示 **"稍后阅读"** 的按钮；
问题二，帖子加到 **"稍后阅读"**，后续好像没法看——看不到 **"稍后阅读"** 里面的文章列表。

![image](https://github.com/coolpace/V2EX_Polish/assets/26101369/8e188d01-60aa-43c3-9cf3-82b48d38ac31)

**Comment by Codennnn** [comment]
问题一：目前只能在帖子详情页才能执行“稍后阅读”操作。
问题二：点击"稍后阅读"提示添加列表成功了吗？

**Comment by shenweiyan** [comment]
> 问题一：目前只能在帖子详情页才能执行“稍后阅读”操作。 

好的，谢谢。

> 问题二：点击"稍后阅读"提示添加列表成功了吗？

是的，提示添加列表成功了。

**Comment by shenweiyan** [comment]
> 试试把插件重装一下？

试过了，还是没办法使用；算了，也不纠结了~

**Comment by shenweiyan** [comment]
原来稍后阅读查看的按钮在插件图标上面（而不是在 V2EX 页面上面），需要点击插件图标就可以看到 "稍后阅读" 的按钮了。

现在问题解决了，感谢作者优秀的工具和耐心的回应 🌹
