### ISSUE TITLE
ios safari 是不是失效了

### ISSUE THREAD

**Issue by Attiv** [coolpace/V2EX_Polish#72]
userscript 和 stay 都不行了，MAC 上也不行了

**Comment by msdurex** [comment]
清理一次Cookie就好了，但是登入上了可能出现不加载，包括节点选择界面都没了。

**Comment by Codennnn** [comment]
Safari 中只有主题列表页是失效的，但其他页面都是正常的，目前还不清楚是什么原因造成的...

<img width="1548" alt="image" src="https://github.com/coolpace/V2EX_Polish/assets/47730755/c30d4def-1e2a-4d50-b702-a92108e33cd1">
<img width="1586" alt="image" src="https://github.com/coolpace/V2EX_Polish/assets/47730755/b6a72f10-7403-41e2-bd2e-4aef627b1b86">
