### ISSUE TITLE
自动签到失效

### ISSUE THREAD

**Issue by Ares-Chang** [coolpace/V2EX_Polish#73]
您好，我在使用插件的时候配置了 Api token 并开启了自动签到，但是每天打开并不生效

并且我点击这里的签到跳转页面签到时会报错，无法签到成功

![image](https://github.com/coolpace/V2EX_Polish/assets/36911513/a7c7e3bf-987b-44ec-8ee4-c88e7a1ca3fb)

![image](https://github.com/coolpace/V2EX_Polish/assets/36911513/7ffe326c-c6aa-4f35-88fd-e0ed67d352af)

我使用的是 Chrome 插件，版本是 `1.9.15`

Chrome 版本为 `122.0.6261.112 (正式版本) （64 位） (cohort: Stable) `

感谢！

**Comment by Codennnn** [comment]
![image](https://github.com/coolpace/V2EX_Polish/assets/47730755/54333edc-258d-4b19-9757-016917260c01)

这里有无法签到的提示，需要你排查下是什么问题呢，我自己的自动签到功能一直是正常的。

**Comment by Ares-Chang** [comment]
抱歉，我以为这是 v2ex 对用了插件的用户的提示😅，感谢
