### ISSUE TITLE
CDN二级域名跨域，导致预加载多页回复失败

### ISSUE THREAD

**Issue by gricn** [coolpace/V2EX_Polish#76]
今天在访问v2ex过程中，也遇到了 #47 所描述预加载多页失败。通过分析发现是由于CORS所致。

## 分析过程

首先，v2ex有众多二级域名，最常见的如`www`, `global`, `hk`, `cn`等。正如Livid在[该回复](https://www.v2ex.com/t/559587#r_7252923)谈及：
> V2EX二级域名是用来测试不同的 CDN 的域名。

而目前上述4个二级域名均被该插件支持。

其次，由于用户访问IP差异，如打开某热门回答，会进入hk二级域名。如：https://hk.v2ex.com/t/1029673?p=1. 但在预加载多页过程中，由于代码层默认访问的是Origin是`V2EX.Origin`，也就是`https://www.v2ex.com`，所以会请求访问https://www.v2ex.com/t/1029673?p=2. 此时由于域名不同，不符合CORS原则，且v2ex站点服务器端没有设置`Access-Control-Allow-Origin`，将导致预加载失败。

## 解决思路
将`V2EX.Origin`修改成`window.location.origin`

**Comment by gricn** [comment]
[#78 ](https://github.com/coolpace/V2EX_Polish/pull/78) 已发pr，在本地Chrome测试没有问题

**Comment by Codennnn** [comment]
感谢你的贡献，该问题已被改善～
