### ISSUE TITLE
在邀请码页面页脚渲染有问题

### ISSUE THREAD

**Issue by kierankihn** [coolpace/V2EX_Polish#79]
链接：https://www.v2ex.com/settings/invite

页脚会变成：

![image](https://github.com/coolpace/V2EX_Polish/assets/114803508/9ececcbf-9593-41e9-918b-c7fbe01c641e)

关闭插件之后：

![image](https://github.com/coolpace/V2EX_Polish/assets/114803508/031be66a-40f3-4627-8ad6-ebcf1919bf65)

**Comment by Codennnn** [comment]
该问题已修复，谢谢反馈。
