### ISSUE TITLE
帖子置顶标识

### ISSUE THREAD

**Issue by orionna319** [coolpace/V2EX_Polish#80]
感谢作者提供的插件，让我使用v2ex更加便捷，感谢作者大大。我在使用过程中，发现v2ex原来还有置顶这一说，使用插件后发现帖子列表没有置顶标识。

原站-有置顶标识
![image](https://github.com/coolpace/V2EX_Polish/assets/85230052/da5578ef-2da1-4e4d-85a8-5ae1dc32df7a)
![image](https://github.com/coolpace/V2EX_Polish/assets/85230052/826a1583-1887-4c2c-b838-975ed9b6324a)

使用插件后-无置顶标识
![image](https://github.com/coolpace/V2EX_Polish/assets/85230052/e03ab918-71c8-4ef3-91af-e1d7ff048c81)

**Comment by orionna319** [comment]
[corner_star.png](https://www.v2ex.com/static/img/corner_star.png)

**Comment by Codennnn** [comment]
v1.9.24 修复了这个问题。

**Comment by Codennnn** [comment]
这个改动先撤回了，貌似这个角标也不是「置顶」的意思。
