### ISSUE TITLE
最热数据不更新

### ISSUE THREAD

**Issue by oneisall8955** [coolpace/V2EX_Polish#81]
![image](https://github.com/coolpace/V2EX_Polish/assets/44989283/fe01c3fd-31ba-45fe-95b6-1809ca4c49cc)
如图，扩展里面的最热数据一直不更新

**Comment by Codennnn** [comment]
在我这里看到的「最热」还是正常新的数据，要不你重装插件试试看？

<img width="514" alt="image" src="https://github.com/coolpace/V2EX_Polish/assets/47730755/978ff7cc-be74-4c50-9bf1-46293f4c504d">

**Comment by oneisall8955** [comment]
重新安装了，仍然是旧的数据，4天前的了

**Comment by oneisall8955** [comment]
最热这个tab，没有请求v2ex接口，怀疑从本地文件查找了？

**Comment by oneisall8955** [comment]
看源码，不清楚是不是访问：GET https://wbhvzt9dzy.us.aircode.run 这个接口获取数据的原因，可能我这边网络有问题

**Comment by Codennnn** [comment]
Popup 里的「最热」数据是通过 `https://v2ex.com/api/topics/hot.json` 获取的，你可以在本地请求这个接口查看数据是不是正常的。

**Comment by oneisall8955** [comment]
> Popup 里的「最热」数据是通过 `https://v2ex.com/api/topics/hot.json` 获取的，你可以在本地请求这个接口查看数据是不是正常的。

接口是正常的：
![image](https://github.com/coolpace/V2EX_Polish/assets/44989283/5f60d31a-5920-4e44-b9e8-c0d5fe4d99ff)

插件仍然是旧的数据：
![image](https://github.com/coolpace/V2EX_Polish/assets/44989283/00291b17-5c3f-4e3c-8949-d1326459f049)

**Comment by Codennnn** [comment]
这个问题好像的确是存在的，我正在着手解决👐🏻。

**Comment by Codennnn** [comment]
v1.9.25 已经解决这个问题啦，非常感谢你的反馈，你让 V2EX Polish 变得更好用了！
