### ISSUE TITLE
更好的回复优化

### ISSUE THREAD

**Issue by jiz4oh** [coolpace/V2EX_Polish#83]
现在在一条帖子艾特多人的情况下，默认会将回复添加到第一个帖子后面。可以考虑两个方案：

1. 分拆：将对应的回复信息添加到对应的帖子下面
2. 调整：将回复添加到最后一个帖子后面，这样感觉会更合理一些

**Comment by Codennnn** [comment]
第 1 点：如果把回复拆分成多条，那么就实现不了对某条被拆分的回复进行「点赞」和「屏蔽」。
第 2 点：以前实现过，但是有人不满意这种处理方式，所以就恢复为现在的形式。

**Comment by Codennnn** [comment]
可以考虑。

**Comment by Codennnn** [comment]
今天查看控制选项时，发现已经支持这个功能了，开启后就能让 @ 多人的回复参与嵌套。

<img width="350" alt="image" src="https://github.com/coolpace/V2EX_Polish/assets/47730755/ec81e21b-1c6b-468d-bff5-7117ef638be8">

**Comment by jiz4oh** [comment]
已勾选表示是会将回复添加到最后一个帖子后面吗？没看懂这个参与嵌套是什么意思

**Comment by Codennnn** [comment]
就是会添加到最后一条回复后面的意思。

**Comment by jiz4oh** [comment]
@Codennnn 
![image](https://github.com/coolpace/V2EX_Polish/assets/41264693/ea91f299-a7a3-4da4-b7dc-fc4a3346a1b6)
这个是关闭时的显示

![image](https://github.com/coolpace/V2EX_Polish/assets/41264693/0ebb1a40-e5d5-4bdf-bbfb-215628980712)
这个是开启时的显示，被添加到第一条回复后面了


可以看看是 bug 吗？这是测试帖子的[链接](https://www.v2ex.com/t/1042207)

**Comment by Codennnn** [comment]
v1.10.5 修复了这个问题。

<img width="810" alt="image" src="https://github.com/coolpace/V2EX_Polish/assets/47730755/1c4dad03-beae-4f13-a299-dd006bf796fc">

**Comment by jiz4oh** [comment]
非常感谢！
