### ISSUE TITLE
不自动签到了

### ISSUE THREAD

**Issue by Dagsi** [coolpace/V2EX_Polish#88]

**Comment by Codennnn** [comment]
将插件更新到最新版本 v1.10.7 后试试。

**Comment by LavaCxx** [comment]
> 将插件更新到最新版本 v1.10.7 后试试。

失败的话，一般是因为v2那边报“你的浏览器有一些奇奇怪怪的设置，请用一个干净安装的浏览器重试一下吧”，试了下和user-agent没关系

**Comment by yang-han** [comment]
对，但是手动签就一直没问题，自动签到就会报“你的浏览器有一些奇奇怪怪的设置，请用一个干净安装的浏览器重试一下吧”，不清楚是哪里不一样

**Comment by LavaCxx** [comment]
> 对，但是手动签就一直没问题，自动签到就会报“你的浏览器有一些奇奇怪怪的设置，请用一个干净安装的浏览器重试一下吧”，不清楚是哪里不一样

上周参数换了一大堆，后来发现应该是cookie问题，但具体缺了哪部分就不知道了。
