### ISSUE TITLE
预览不能用了？

### ISSUE THREAD

**Issue by Qroxyquan** [coolpace/V2EX_Polish#89]
预览打开提示【加载主题失败，点击重试。】

**Comment by Codennnn** [comment]
是不是没登录账号？

**Comment by ceynri** [comment]
应该是 token 过期了。我也遇到这个问题好几天了，刚重新申请 token 后填入 v2ex polish 就 ok 了。
这里如果可以判断出 token 过期的情况的话，感觉可以优化一下，引导用户重新申请 token

**Comment by Codennnn** [comment]
> 应该是 token 过期了。我也遇到这个问题好几天了，刚重新申请 token 后填入 v2ex polish 就 ok 了。 这里如果可以判断出 token 过期的情况的话，感觉可以优化一下，引导用户重新申请 token

感谢建议，已增加 token 失效的提示。
