### ISSUE TITLE
移动端适配问题

### ISSUE THREAD

**Issue by lovezsh** [coolpace/V2EX_Polish#9]
f12 打开移动端模拟器，没有适配

![image](https://user-images.githubusercontent.com/65840178/232683982-bc48a8a3-f5e7-4cfc-86a1-8eb24f44c0e5.png)

**Comment by Codennnn** [comment]
目前扩展只针对桌面端的页面进行改造，因为一般来说移动端的网页对扩展的支持不好。像你这用桌面浏览器模拟移动设备去浏览的，有点属于特殊情况了......
