### ISSUE TITLE
V2EX_Polish: 无法设置 member-tag， 单个 item 不能超出 8 KB

### ISSUE THREAD

**Issue by LieWell** [coolpace/V2EX_Polish#90]
最近在设置用户标签时报错
<img width="977" alt="image" src="https://github.com/user-attachments/assets/9e4a4b40-07a7-4e11-8f0d-ab9a7a564ff4">

**Comment by LieWell** [comment]
总数不能超过8K，有点不够用
<img width="357" alt="image" src="https://github.com/user-attachments/assets/48a99935-fbc5-4420-a337-5b40829fab03">

**Comment by Codennnn** [comment]
这个容量受限于 Chrom 插件的规定，无法调整呢。

**Comment by LieWell** [comment]
有点难受☹️
