### ISSUE TITLE
预览界面与vimium插件不兼容

### ISSUE THREAD

**Issue by 2han9wen71an** [coolpace/V2EX_Polish#91]
在插件默认的预览模式下，如果使用键盘上的 "j" 和 "k" 键来上下滚动预览界面，需要先点击预览界面的内容，以确保焦点位于顶层预览窗口。在此之前，"j" 和 "k" 键将控制的是底部内容的滚动。

**Comment by Codennnn** [comment]
v1.10.18 改善了这个问题，谢谢提醒。

**Comment by Codennnn** [comment]
一直以来的交互都是：手动悬浮到标题后面才显示预览按钮。
