### ISSUE TITLE
显示被@用户本帖的发言内容

### ISSUE THREAD

**Issue by PctAIGM** [coolpace/V2EX_Polish#93]
由于楼中楼功能有时候展示回有问题，不太准确。所以一般都关闭楼中楼。
但有时候想看下被@用户的发言就得通过搜索翻，不太方便。

希望在帖子中点击 @xxxx，能弹窗展示被@用户本帖的发言

**Comment by PctAIGM** [comment]
https://v2ex.com/t/1071947?p=2#reply170

例如这种，翻页后的楼中楼体验就不是很好

**Comment by Codennnn** [comment]
我评估了一下，目前要实现你描述的这种需求，是有点困难的。
不过有个折衷的方案，就是你点击回到第一页，这样就能通过预加载两页的评论，从而看到完整的评论了。
