### ISSUE TITLE
Arc 浏览器无法打开选项设置

### ISSUE THREAD

**Issue by plzzzzg** [coolpace/V2EX_Polish#94]
Arc 版本1.60.0 (53678)
Chromium Engine Version 128.0.6613.138
![image](https://github.com/user-attachments/assets/ef1e47a7-cd55-4c9c-ae26-d3311f1e9050)

**Comment by Codennnn** [comment]
你安装的 V2EX Polish 是最新的吗，我这边是正常能够打开设置页的。

https://github.com/user-attachments/assets/4f8d6fd9-6401-45c8-806d-ea06fdf8f0b4

**Comment by plzzzzg** [comment]
通过 tamper monkey 安装的 1.10.21 不行，但从 Chrome 插件应用商店安装的可以正常打开，谢谢。
![image](https://github.com/user-attachments/assets/2f7f7bea-e667-4c2b-995c-e9b520027f60)

**Comment by Codennnn** [comment]
用油猴脚本的话是没有配置选项的，只有 Chrome 扩展才有。
