### ISSUE TITLE
设置不显示，重装也无效

### ISSUE THREAD

**Issue by kokojacket** [coolpace/V2EX_Polish#95]
![image](https://github.com/user-attachments/assets/9c94369f-88aa-40f4-a4d9-dddc111afcab)

**Comment by declandragon** [comment]
夜间模式无法开启。关闭插件可以正常开启。 
* 版本 1.10.23

**Comment by Surgeol** [comment]
存在相同问题

**Comment by theotop97** [comment]
存在相同问题

**Comment by Tomorrowxxy** [comment]
1.11.0 没有解决颜色主题问题，在扩展设置页面开启白色，在 v2 帖子页面无法开启深色页面

**Comment by nixgnauhcuy** [comment]
存在相同问题

**Comment by Codennnn** [comment]
各位反馈的问题，均已修复好了～

**Comment by Tomorrowxxy** [comment]
> 1.11.0 没有解决颜色主题问题，在扩展设置页面开启白色，在 v2 帖子页面无法开启深色页面

@Codennnn  如何单独设置插件页面是浅色模式， v2 帖子页面是深色模式？之前是支持的，当前变为同步了，很不习惯
