### ISSUE TITLE
油猴脚本夜间模式失效

### ISSUE THREAD

**Issue by hushenghao** [coolpace/V2EX_Polish#98]
使用的是油猴版本

* Chrome版本: 129.0.6668.91
* 油猴版本: v5.2.3
* 插件版本: 1.11.4

<img width="1126" alt="image" src="https://github.com/user-attachments/assets/f52f4b11-61ec-4451-92fe-95849983e6cd">

换成Chrome插件版本夜间模式可以正常使用

**Comment by Codennnn** [comment]
这是 V2EX Polish 油猴脚本的一个已知问题，最新的代码其实是已经修复了这个问题的，但是在 Greasy Fork 发布不了，一点击发布就出现 502。

你可以先用浏览器插件来解决这个问题。
<img width="483" alt="image" src="https://github.com/user-attachments/assets/2701da2e-d4d4-4162-ac70-c7926708ecd0">

**Comment by Codennnn** [comment]
不会呀，我这是可以正常根据系统来切换亮暗主题的：
https://github.com/user-attachments/assets/bbfffe5a-dbd5-4855-bb8c-ecb9295265f5
